// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domainmodel "cats/domain/model"

	mock "github.com/stretchr/testify/mock"

	model "cats/repo/model"
)

// CatsMapper is an autogenerated mock type for the CatsMapper type
type CatsMapper struct {
	mock.Mock
}

// Map provides a mock function with given fields: cats
func (_m *CatsMapper) Map(cats []model.CatDto) []domainmodel.Cat {
	ret := _m.Called(cats)

	var r0 []domainmodel.Cat
	if rf, ok := ret.Get(0).(func([]model.CatDto) []domainmodel.Cat); ok {
		r0 = rf(cats)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domainmodel.Cat)
		}
	}

	return r0
}
